system: "Lift"
paths:
  input:
    main: "resources/input/lift/"
    dt: "04.5-simulation/"
    dt_files:
      - "cutBajada_4_0_4.csv"
      #- "cutBajada_4_2_0_2_4.csv"
      #- "cutBajada_4_3_2_1_0_1_2_3_4.csv"
    pt: "03.55-derived_values/"
    pt_files:
      - "Bajada_4_0_4"
      #- "Bajada_4_2_0_2_4"
      #- "Bajada_4_3_2_1_0_1_2_3_4"
  output: "resources/output/evaluation/lift/elevate/"

labels:
  timestamp_label: "timestamp(s)"
  param_interest: "accel(m/s2)"
  params:
    - "accel(m/s2)"

ranges:
  mad:
    start: 0.00
    step: 0.02
    end: 0.32
  low:
    start: 200
    step: 1
    end: 201
  init_gap:
    start: -1.0
    step: 1.1
    end: 0.0
  cont_gap:
    start: -0.1
    step: 0.11
    end: 0.0
