system: "Lift"
paths:
  input:
    main: "resources/input/lift/"
    dt: "04.5-simulation/"
    dt_files:
      - "cutBajada_4_0_4.csv"
      #- "cutBajada_4_2_0_2_4.csv"
      #- "cutBajada_4_3_2_1_0_1_2_3_4.csv"
    pt: "03.55-derived_values/"
    pt_files:
      - "Bajada_4_0_4_01"
  output: "resources/output/lift/"

labels:
  timestamp_label: "timestamp(s)"
  param_interest: "accel(m/s2)"

ranges:
  mad:
    start: 0.15
    step: 0.02
    end: 0.16
  low:
    start: 200
    step: 10
    end: 205
  init_gap:
    start: 0.0
    step: 0.5
    end: 1.1
