timestamp_label: 'timestep(t)'

# Sliding Window configuration
sliding_window:
  interval_period: 20
  interval_duration: 100

# RabbitMQ configuration
rabbitmq:
  host: 'localhost'
  port: 5670
  prefetch_count: 1

# Databases configuration
influxdb:
  url: 'http://localhost:8086'
  org: 'uma'
  token_path: 'INFLUXDB_TOKEN.txt'
  bucket: 'alignments'

mongodb:
  host: 'localhost'
  port: 27017